site_name: http4k Connect
site_url: https://connect.http4k.org/
site_description: http4k Connect is a lightweight API adapter toolkit which includes libraries for connecting to popular third-party cloud services and AI backends
site_author: David Denton (@daviddenton), Ivan Sanchez (@s4nchez)
copyright: 'Copyright &copy; 2024 - David Denton (@daviddenton), IvanSanchez (@s4nchez)'
remote_branch: master
repo_url: https://github.com/http4k/http4k-connect/
theme:
  name: 'material'
  custom_dir: ./docs/theme
  static_templates:
      - ./index.html
  palette:
    primary: 'indigo'
    accent: 'blue'
  logo: img/logo_1100x200_white_on_blue_trans.png
google_analytics: ['UA-125143867-1', 'auto']
markdown_extensions:
  - meta
  - codehilite
  - toc:
      permalink: True
      separator: "_"
extra_css:
  - ./css/site.css
extra:
  logo: img/logo_1100x200_white_on_blue_trans.png
edit_uri: edit/master/src/docs/
strict: false
nav:
  - Introduction: documentation/index.md
  - Changelog: changelog/index.md
  - Contribute/support http4k: contributing/index.md
  - Code of Conduct: code-of-conduct/index.md
  - Gradle KSP Plugin: guide/reference/http4k-connect-ksp-generator/index.md
  - AI:
    - LangChain: guide/reference/ai/langchain/index.md
    - LMStudio: guide/reference/ai/lmstudio/index.md
    - Ollama: guide/reference/ai/ollama/index.md
    - OpenAI: guide/reference/ai/openai/index.md
  - AWS:
    - App Runner: guide/reference/amazon/apprunner/index.md
    - Cloudfront: guide/reference/amazon/cloudfront/index.md
    - Cloudwatch Logs: guide/reference/amazon/cloudwatchlogs/index.md
    - Cognito: guide/reference/amazon/cognito/index.md
    - Container Credentials: guide/reference/amazon/containercredentials/index.md
    - DynamoDB: guide/reference/amazon/dynamodb/index.md
    - EventBridge: guide/reference/amazon/eventbridge/index.md
    - Evidently: guide/reference/amazon/evidently/index.md
    - Firehose: guide/reference/amazon/firehose/index.md
    - IAM Identity Center: guide/reference/amazon/iamidentitycenter/index.md
    - Instance Metadata: guide/reference/amazon/instancemetadata/index.md
    - KMS: guide/reference/amazon/kms/index.md
    - Lambda: guide/reference/amazon/lambda/index.md
    - S3: guide/reference/amazon/s3/index.md
    - Secrets Manager: guide/reference/amazon/secretsmanager/index.md
    - SES: guide/reference/amazon/ses/index.md
    - SNS: guide/reference/amazon/sns/index.md
    - SQS: guide/reference/amazon/sqs/index.md
    - STS: guide/reference/amazon/sts/index.md
    - Systems Manager: guide/reference/amazon/systemsmanager/index.md
  - GitHub: guide/reference/github/index.md
  - GitLab: guide/reference/gitlab/index.md
  - Google:
    - Analytics UA: guide/reference/google/analytics-ua/index.md
    - Analytics V4: guide/reference/google/analytics-ga4/index.md
  - Kafka:
    - REST Gateway: guide/reference/kafka/rest/index.md
    - Schema Registry: guide/reference/kafka/schemaregistry/index.md
  - Mattermost: guide/reference/mattermost/index.md
  - Storage:
    - File: guide/reference/storage/core/index.md
    - HTTP: guide/reference/storage/http/index.md
    - In-Memory: guide/reference/storage/core/index.md
    - JDBC: guide/reference/storage/jdbc/index.md
    - Redis: guide/reference/storage/redis/index.md
    - S3: guide/reference/storage/s3/index.md
