site_name: http4k Connect
site_url: https://connect.http4k.org/
site_description: http4k-connect is a set of lightweight API libraries for connecting to popular third-party cloud services and AI backends
site_author: David Denton (@daviddenton), Ivan Sanchez (@s4nchez)
copyright: 'Copyright &copy; 2024 - David Denton (@daviddenton), IvanSanchez (@s4nchez)'
remote_branch: master
repo_url: https://github.com/http4k/http4k-connect/
theme:
  name: 'material'
  custom_dir: ./docs/theme
  static_templates:
      - ./index.html
  palette:
    primary: 'indigo'
    accent: 'blue'
  logo: img/logo_1100x200_white_on_blue_trans.png
google_analytics: ['UA-125143867-1', 'auto']
markdown_extensions:
  - meta
  - codehilite
  - toc:
      permalink: True
      separator: "_"
extra_css:
  - ./css/site.css
extra:
  logo: img/logo_1100x200_white_on_blue_trans.png
edit_uri: edit/master/src/docs/
strict: false
nav:
  - Introduction: documentation/index.m
  - Changelog: changelog/index.md
  - Contribute/support http4k: contributing/index.md
  - Code of Conduct: code-of-conduct/index.md
  - Gradle KSP Plugin: documentation/http4k-connect-ksp-generator/index.md
  - AI:
    - LangChain: documentation/ai/langchain/index.md
    - LMStudio: documentation/ai/lmstudio/index.md
    - Ollama: documentation/ai/ollama/index.md
    - OpenAI: documentation/ai/openai/index.md
  - AWS:
    - App Runner: documentation/amazon/apprunner/index.md
    - Cloudfront: documentation/amazon/cloudfront/index.md
    - Cloudwatch Logs: documentation/amazon/cloudwatchlogs/index.md
    - Cognito: documentation/amazon/cognito/index.md
    - Container Credentials: documentation/amazon/containercredentials/index.md
    - DynamoDB: documentation/amazon/dynamodb/index.md
    - EventBridge: documentation/amazon/eventbridge/index.md
    - Evidently: documentation/amazon/evidently/index.md
    - Firehose: documentation/amazon/firehose/index.md
    - IAM Identity Center: documentation/amazon/iamidentitycenter/index.md
    - Instance Metadata: documentation/amazon/instancemetadata/index.md
    - KMS: documentation/amazon/kms/index.md
    - Lambda: documentation/amazon/lambda/index.md
    - S3: documentation/amazon/s3/index.md
    - Secrets Manager: documentation/amazon/secretsmanager/index.md
    - SES: documentation/amazon/ses/index.md
    - SNS: documentation/amazon/sns/index.md
    - SQS: documentation/amazon/sqs/index.md
    - STS: documentation/amazon/sts/index.md
    - Systems Manager: documentation/amazon/systemsmanager/index.md
  - GitHub: documentation/github/index.md
  - GitLab: documentation/gitlab/index.md
  - Google:
    - Analytics UA: documentation/google/analytics-ua/index.md
    - Analytics V4: documentation/google/analytics-ga4/index.md
  - Kafka:
    - REST Gateway: documentation/kafka/rest/index.md
    - Schema Registry: documentation/kafka/schemaregistry/index.md
  - Mattermost: documentation/mattermost/index.md
  - Storage:
    - File: documentation/storage/core/index.md
    - HTTP: documentation/storage/http/index.md
    - In-Memory: documentation/storage/core/index.md
    - JDBC: documentation/storage/jdbc/index.md
    - Redis: documentation/storage/redis/index.md
    - S3: documentation/storage/s3/index.md
