site_name: http4k Connect
site_url: https://connect.http4k.org/
site_description: http4k-connect is a set of lightweight API libraries for connecting to popular third-party cloud services and AI backends
site_author: David Denton (@daviddenton), Ivan Sanchez (@s4nchez)
copyright: 'Copyright &copy; 2024 - David Denton (@daviddenton), IvanSanchez (@s4nchez)'
remote_branch: master
repo_url: https://github.com/http4k/http4k-connect/
theme:
  name: 'material'
  custom_dir: ./docs/theme
  static_templates:
      - ./index.html
  palette:
    primary: 'indigo'
    accent: 'blue'
  logo: img/logo_1100x200_white_on_blue_trans.png
google_analytics: ['UA-125143867-1', 'auto']
markdown_extensions:
  - meta
  - codehilite
  - toc:
      permalink: True
      separator: "_"
extra_css:
  - ./css/site.css
extra:
  logo: img/logo_1100x200_white_on_blue_trans.png
edit_uri: edit/master/src/docs/
strict: false
nav:
  - Introduction: documentation/index.md
  - Changelog: changelog/index.md
  - Contribute/support http4k: contributing/index.md
  - Code of Conduct: code-of-conduct/index.md
  - AI:
    - LangChain: reference/ai/langchain/index.md
    - LMStudio: reference/ai/lmstudio/index.md
    - Ollama: reference/ai/ollama/index.md
    - OpenAI: reference/ai/openai/index.md
  - AWS:
    - App Runner: reference/amazon/apprunner/index.md
    - Cloudfront: reference/amazon/cloudfront/index.md
    - Cloudwatch Logs: reference/amazon/cloudwatchlogs/index.md
    - Cognito: reference/amazon/cognito/index.md
    - Container Credentials: reference/amazon/containercredentials/index.md
    - DynamoDB: reference/amazon/dynamodb/index.md
    - EventBridge: reference/amazon/eventbridge/index.md
    - Evidently: reference/amazon/evidently/index.md
    - Firehose: reference/amazon/firehose/index.md
    - IAM Identity Center: reference/amazon/iamidentitycenter/index.md
    - Instance Metadata: reference/amazon/instancemetadata/index.md
    - KMS: reference/amazon/kms/index.md
    - Lambda: reference/amazon/lambda/index.md
    - S3: reference/amazon/s3/index.md
    - Secrets Manager: reference/amazon/secretsmanager/index.md
    - SES: reference/amazon/ses/index.md
    - SNS: reference/amazon/sns/index.md
    - SQS: reference/amazon/sqs/index.md
    - STS: reference/amazon/sts/index.md
    - Systems Manager: reference/amazon/systemsmanager/index.md
  - GitHub: reference/github/index.md
  - GitLab: reference/gitlab/index.md
  - Google:
    - Analytics UA: reference/google/analytics-ua/index.md
    - Analytics V4: reference/google/analytics-ga4/index.md
  - Kafka:
    - REST Gateway: reference/kafka/rest/index.md
    - Schema Registry: reference/kafka/schemaregistry/index.md
  - Mattermost: reference/mattermost/index.md
