name: Update Website
on:
  push:
    branches:
      - master
permissions:
  contents: read

jobs:
  release-site:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.12.4'
          architecture: 'x64'
      - run: pip install -r requirements.txt
      - uses: actions/checkout@v4.2.0
        with:
          repository: http4k/www-http4k-connect
          path: tmp
          token: ${{ secrets.TOOLBOX_REPO_TOKEN }}
      - run: pushd src && mkdocs gh-deploy && popd

